#version 430 core
#include "common.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer ParticlesInput
{
    Particle particles[];
};

layout(location = 0) uniform float dt;

void main() {
    uint id = gl_GlobalInvocationID.x;
    particles[id].velosity += particles[id].acceleration * dt;
    particles[id].position += particles[id].velosity * dt;
}