#version 430 core
#include "../../common.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer GridColumnCountsOutput
{
	int grid_column_counts[];
};
layout(std430, binding = 1) buffer GridColumnOffsetsOutput
{
	int grid_column_offsets[];
};

layout(location = 0) uniform ivec2 grid_size;

void main() {
	for (uint i = 1; i < grid_size.y; ++i) {
		grid_column_offsets[i] = grid_column_counts[i-1] + grid_column_offsets[i - 1];
	}
}
