#version 430 core
#include "../../common.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(location = 0) uniform float dt;

void main() {
	uint id = particle_indexes[gl_GlobalInvocationID.x];
	particles[id].velosity += particles[id].acceleration * dt;
	particles[id].velosity += particles[id].applied_impulse;
	particles[id].applied_impulse = vec2(0);
	particles[id].position += particles[id].velosity * dt;
}